import { type NextPage } from "next";
import Head from "next/head";
import { Timeline } from "../components/timeline/Timeline";
import { NewTweetForm } from "../components/newTweetForm/NewTweetForm";
import { useIsAuthenticated } from "../hooks/useIsAuthenticated";

const Home: NextPage = () => {
  const isAuthenticated = useIsAuthenticated();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-4">
        {isAuthenticated && <NewTweetForm />}
        <Timeline />
      </div>
    </>
  );
};

export default Home;
