import { type NextPage } from "next";
import Head from "next/head";
import { Timeline } from "../components/timeline/Timeline";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-4">
        <Timeline />
      </div>
    </>
  );
};

export default Home;
